version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      - elixir-artifacts:/opt/elixir-artifacts
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      ELIXIR_BUILD_PATH: /opt/elixir-artifacts/_build
      ELIXI_DEPS_PATH: /opt/elixir-artifacts/deps
    command: "mix phx.server"
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: {}
  elixir-artifacts: {}
