version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - db
    command: "elixir --sname sample@app --cookie sample -S mix phx.server"
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
  livebook:
    image: ghcr.io/livebook-dev/livebook
    volumes:
      - ./docs:/data
    ports:
      - 8080:8080
    environment:
      - LIVEBOOK_COOKIE=sample
      - LIVEBOOK_DEFAULT_RUNTIME=attached:sample@app:sample
      - LIVEBOOK_TOKEN_ENABLED=false
      - LIVEBOOK_HOME=/data

volumes:
  dbdata: {}
